import Head from 'next/head'
import { HeaderSection } from '../components/01-sections/HeaderSection'
import { BannerSection } from '../components/01-sections/BannerSection'
import { MainSection } from '../components/01-sections/MainSection'
import { ProfileSection } from '../components/01-sections/ProfileSection'
import { ProjectsSection } from '../components/01-sections/ProjectsSection'
import { FooterSection } from '../components/01-sections/FooterSection'
import { getSession } from "next-auth/react"

export default function HomePage({session}) {

	return (
		<>
			<Head>
				<title>Behance</title>
				<meta name="description" content="Generated by Ricardo Oliva Alonso" />
				<link rel="icon" href="/favicon.png" />
			</Head>
			<HeaderSection />
			<BannerSection />
			<MainSection grid="2">
				<ProfileSection />
				<ProjectsSection />
			</MainSection>
			<FooterSection />
		</>
	)
}

export const getServerSideProps = async(context) => {
	const session = await getSession(context) 
	return {
		props: {
			session
		}
	}
}
